openapi: 3.1.0
info:
  title: Anthropic Messages API - Streaming
  version: "2023-06-01"
  description: |
    Anthropic Claude API 的流式响应规范。

    使用 Server-Sent Events (SSE) 格式返回流式数据。

    支持的事件类型：
    - message_start - 消息开始
    - content_block_start - 内容块开始
    - content_block_delta - 内容增量
    - content_block_stop - 内容块结束
    - message_delta - 消息增量
    - message_stop - 消息结束
    - ping - 心跳
    - error - 错误

  contact:
    name: Anthropic
    url: https://www.anthropic.com

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.anthropic.com
    description: Anthropic API Production

security:
  - ApiKeyHeader: []

paths:
  /v1/messages:
    post:
      operationId: createMessageStreaming
      summary: 创建消息（流式）
      description: |
        向 Claude 模型发送消息并以流式方式获取响应。

        需要在请求中设置 `"stream": true`。
        响应使用 Server-Sent Events (SSE) 格式。

      parameters:
        - name: anthropic-version
          in: header
          required: true
          schema:
            type: string
            default: "2023-06-01"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/MessagesRequest'
                - type: object
                  required:
                    - stream
                  properties:
                    stream:
                      type: boolean
                      enum:
                        - true
                      description: 必须设置为true以启用流式响应

            examples:
              streamingRequest:
                summary: 流式请求
                value:
                  model: claude-3-5-sonnet-20241022
                  max_tokens: 1024
                  stream: true
                  messages:
                    - role: user
                      content: Write a short poem about the ocean

      responses:
        '200':
          description: 流式响应（SSE格式）
          content:
            text/event-stream:
              schema:
                type: string
                description: |
                  Server-Sent Events 流。
                  每个事件格式为：

                  ```
                  event: <event_type>
                  data: <json_data>

                  ```

              examples:
                streamingResponse:
                  summary: 流式响应示例
                  value: |
                    event: message_start
                    data: {"type":"message_start","message":{"id":"msg_abc","type":"message","role":"assistant","content":[],"model":"claude-3-5-sonnet-20241022","usage":{"input_tokens":10,"output_tokens":0}}}

                    event: content_block_start
                    data: {"type":"content_block_start","index":0,"content_block":{"type":"text","text":""}}

                    event: content_block_delta
                    data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"The"}}

                    event: content_block_delta
                    data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" ocean"}}

                    event: content_block_stop
                    data: {"type":"content_block_stop","index":0}

                    event: message_delta
                    data: {"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":15}}

                    event: message_stop
                    data: {"type":"message_stop"}

components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header
      name: x-api-key

  schemas:
    MessagesRequest:
      type: object
      required:
        - model
        - max_tokens
        - messages
        - stream
      properties:
        model:
          type: string
        max_tokens:
          type: integer
        messages:
          type: array
          items:
            type: object
        stream:
          type: boolean
          const: true

    # ==================== Streaming Events ====================

    MessageStartEvent:
      type: object
      required:
        - type
        - message
      properties:
        type:
          type: string
          enum:
            - message_start
        message:
          $ref: '#/components/schemas/StreamingMessage'
      description: |
        消息开始事件。
        包含初始消息信息（不含content）和usage统计。

    StreamingMessage:
      type: object
      required:
        - id
        - type
        - role
        - content
        - model
        - usage
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - message
        role:
          type: string
          enum:
            - assistant
        content:
          type: array
          items: {}
          description: 开始时为空数组
        model:
          type: string
        usage:
          type: object
          properties:
            input_tokens:
              type: integer
            output_tokens:
              type: integer

    ContentBlockStartEvent:
      type: object
      required:
        - type
        - index
        - content_block
      properties:
        type:
          type: string
          enum:
            - content_block_start
        index:
          type: integer
          description: 内容块索引
        content_block:
          oneOf:
            - $ref: '#/components/schemas/TextContentBlock'
            - $ref: '#/components/schemas/ToolUseContentBlock'
      description: |
        内容块开始事件。
        标记新的内容块（text或tool_use）的开始。

    TextContentBlock:
      type: object
      required:
        - type
        - text
      properties:
        type:
          type: string
          enum:
            - text
        text:
          type: string
          description: 初始为空字符串

    ToolUseContentBlock:
      type: object
      required:
        - type
        - id
        - name
        - input
      properties:
        type:
          type: string
          enum:
            - tool_use
        id:
          type: string
        name:
          type: string
        input:
          type: object
          description: 初始为空对象

    ContentBlockDeltaEvent:
      type: object
      required:
        - type
        - index
        - delta
      properties:
        type:
          type: string
          enum:
            - content_block_delta
        index:
          type: integer
          description: 内容块索引
        delta:
          oneOf:
            - $ref: '#/components/schemas/TextDelta'
            - $ref: '#/components/schemas/InputJsonDelta'
      description: |
        内容块增量事件。
        包含文本增量或工具输入JSON增量。

    TextDelta:
      type: object
      required:
        - type
        - text
      properties:
        type:
          type: string
          enum:
            - text_delta
        text:
          type: string
          description: 文本增量

    InputJsonDelta:
      type: object
      required:
        - type
        - partial_json
      properties:
        type:
          type: string
          enum:
            - input_json_delta
        partial_json:
          type: string
          description: 工具输入的JSON增量

    ContentBlockStopEvent:
      type: object
      required:
        - type
        - index
      properties:
        type:
          type: string
          enum:
            - content_block_stop
        index:
          type: integer
          description: 内容块索引
      description: |
        内容块结束事件。
        标记一个内容块的结束。

    MessageDeltaEvent:
      type: object
      required:
        - type
        - delta
        - usage
      properties:
        type:
          type: string
          enum:
            - message_delta
        delta:
          $ref: '#/components/schemas/MessageDelta'
        usage:
          type: object
          properties:
            output_tokens:
              type: integer
              description: 最终输出token数
      description: |
        消息增量事件。
        包含stop_reason和最终usage统计。

    MessageDelta:
      type: object
      properties:
        stop_reason:
          type: string
          enum:
            - end_turn
            - max_tokens
            - stop_sequence
            - tool_use
          description: 停止原因
        stop_sequence:
          type: string
          description: 触发的停止序列（如果有）

    MessageStopEvent:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - message_stop
      description: |
        消息结束事件。
        标记整个流式响应的结束。

    PingEvent:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - ping
      description: |
        心跳事件。
        用于保持连接活跃。

    ErrorEvent:
      type: object
      required:
        - type
        - error
      properties:
        type:
          type: string
          enum:
            - error
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
      description: |
        错误事件。
        流式传输过程中发生错误时发送。

    # Union type for all streaming events
    StreamEvent:
      oneOf:
        - $ref: '#/components/schemas/MessageStartEvent'
        - $ref: '#/components/schemas/ContentBlockStartEvent'
        - $ref: '#/components/schemas/ContentBlockDeltaEvent'
        - $ref: '#/components/schemas/ContentBlockStopEvent'
        - $ref: '#/components/schemas/MessageDeltaEvent'
        - $ref: '#/components/schemas/MessageStopEvent'
        - $ref: '#/components/schemas/PingEvent'
        - $ref: '#/components/schemas/ErrorEvent'
